import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Headers } from '../components/Header';
import React from 'react';
import { TodoProvider } from 'src/components/TodoContext.tsx';
import Create from 'src/app/todos/create/page.tsx';
import Todos from 'src/app/todos/page.tsx';

const App = () => {
  return (
    <TodoProvider>
      <Create />
      <Todos />
    </TodoProvider>
  );
};

export default App;

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Headers />
        {children}
      </body>
    </html>
  );
}
